### ISSUE TITLE
Support SELECT and TTL commands

### ISSUE THREAD

**Issue by ghost** [ryanlecompte/redis_failover#24]
Hi, I was looking through the code for the failover client, and noticed that SELECT and TTL are not supported. These still have meaning in a failover environment, as many use SELECT to partition their Redis entries between different databases. Similarly, TTL is relevant to check how close to expiry a key is. Key expiration certainly seems like something that is needed.

What is your take on this? What was the rationale behind not supporting those operations in particular?

Thanks!

flu

**Comment by ryanlecompte** [comment]
I actually think those two commands would work just fine. Would you mind forking redis_failover and adding support for them? I'd love to know how they work for you since I personally don't use Redis databases.

**Comment by ryanlecompte** [comment]
Actually, I know I made SELECT an unsupported operation. It's because RedisFailover::Client abstracts away exactly which underlying Redis client will be used for any given operation. For example, you may get a random slave when you perform an operation. I'd have to make SELECT cycle through all of the underlying redis clients and force them all to use a particular database. That's something that I didn't feel necessary in the initial implementation of redis_failover. You can specify a database to use when you initially create the RedisFailover::Client instance. So, if you wanted you could have multiple instances of RedisFailover::Client pointing at different database numbers. 

I think TTL could still work though.

**Comment by ghost** [comment]
I think that providing the DB to the client on creation would work for my SELECT needs. Our services only talk to a particular DB when they are using redis, so the different services could just construct them differently. As for the TTL support, I'd imagine that could just pass through and behave as expected (assuming that Redis replication also replicates key expiration data). 

Unfortunately, I cannot fork and assist due to legal issues :/

Thanks for your quick response!

**Comment by ryanlecompte** [comment]
I added support for TTL in master. Thanks!

**Comment by ghost** [comment]
You're the man. Huge thanks!
