### ISSUE TITLE
No way to pass redis DB when setting up client

### ISSUE THREAD

**Issue by wr0ngway** [ryanlecompte/redis_failover#5]
We use multiple redis DBs, (resque, cache, etc), and usually select them at client initialization time.  There doesn't seem to be a way to pass in the db to the failover client - perhaps other init time options are missing as well?

**Comment by ryanlecompte** [comment]
I haven't added support for Redis databases because it's actually a discouraged feature by the Redis maintainers. They even mention that it will eventually be dropped in a future release. They recommend sharding your data by having separate Redis server/instances (so instead of having one Redis server with 3 databases, have 3 separate servers with a specific data type stored in each).

I'll see if I can add support for specifying databases in RedisFailover::Client this weekend though, along with support for multiple Node Manager daemons. :-)

**Comment by ryanlecompte** [comment]
I just added support in master for specifying the :db option. Note that it will be used for all underlying redis clients that a single RedisFailover::Client uses (master and slaves). So, if you need to use a different db, you'll need to use different RedisFailover::Client instances with a different :db option specified for each. This assumes that all redis servers have the same db's (i..e, all master/slaves have db 0, db 1 .. db N.)
